//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace one.OneDot.Areas.Stocks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_dayDataHistory
    {
        public System.DateTime pDate { get; set; }
        public string stockCOde { get; set; }
        public Nullable<decimal> open { get; set; }
        public Nullable<decimal> high { get; set; }
        public Nullable<decimal> close { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<decimal> price_change { get; set; }
        public Nullable<decimal> p_change { get; set; }
        public Nullable<decimal> ma5 { get; set; }
        public Nullable<decimal> ma10 { get; set; }
        public Nullable<decimal> ma20 { get; set; }
        public Nullable<decimal> v_ma5 { get; set; }
        public Nullable<decimal> v_ma10 { get; set; }
        public Nullable<decimal> v_ma20 { get; set; }
        public Nullable<decimal> turnover { get; set; }
    }
}
