//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace one.OneDot.Areas.Stocks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_lastDayData
    {
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<decimal> changepercent { get; set; }
        public Nullable<decimal> trade { get; set; }
        public Nullable<decimal> open { get; set; }
        public Nullable<decimal> high { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> settlement { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<decimal> turnoverratio { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> per { get; set; }
        public Nullable<decimal> pb { get; set; }
        public Nullable<decimal> mktcap { get; set; }
        public Nullable<decimal> nmc { get; set; }
    }
}
