//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace one.OneDot.Areas.Stocks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_stock_basics_info
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string industry { get; set; }
        public string area { get; set; }
        public Nullable<decimal> pe { get; set; }
        public Nullable<decimal> outstanding { get; set; }
        public Nullable<decimal> totals { get; set; }
        public Nullable<decimal> totalAssets { get; set; }
        public Nullable<decimal> liquidAssets { get; set; }
        public Nullable<decimal> fixedAssets { get; set; }
        public Nullable<decimal> reserved { get; set; }
        public Nullable<decimal> reservedPerShare { get; set; }
        public Nullable<decimal> esp { get; set; }
        public Nullable<decimal> bvps { get; set; }
        public Nullable<decimal> pb { get; set; }
        public Nullable<int> timeToMarket { get; set; }
        public Nullable<decimal> undp { get; set; }
        public Nullable<decimal> perundp { get; set; }
        public Nullable<decimal> rev { get; set; }
        public Nullable<decimal> profit { get; set; }
        public Nullable<decimal> gpr { get; set; }
        public Nullable<decimal> npr { get; set; }
        public Nullable<decimal> holders { get; set; }
    }
}
