//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace one.Res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("one.Res.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 失败次数 的本地化字符串。
        /// </summary>
        public static string AccessFailedCount {
            get {
                return ResourceManager.GetString("AccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆失败，用户名或密码不正确！ 的本地化字符串。
        /// </summary>
        public static string authentication_nameOrPWDError {
            get {
                return ResourceManager.GetString("authentication_nameOrPWDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属角色 的本地化字符串。
        /// </summary>
        public static string BelongToRoles {
            get {
                return ResourceManager.GetString("BelongToRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新  增 的本地化字符串。
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤  销 的本地化字符串。
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删  除 的本地化字符串。
        /// </summary>
        public static string Btn_Del {
            get {
                return ResourceManager.GetString("Btn_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编  辑 的本地化字符串。
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色... 的本地化字符串。
        /// </summary>
        public static string Btn_EditRoles {
            get {
                return ResourceManager.GetString("Btn_EditRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导  出 的本地化字符串。
        /// </summary>
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁  定 的本地化字符串。
        /// </summary>
        public static string Btn_Lock {
            get {
                return ResourceManager.GetString("Btn_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定/解锁 的本地化字符串。
        /// </summary>
        public static string Btn_LockOrUnlock {
            get {
                return ResourceManager.GetString("Btn_LockOrUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登  录 的本地化字符串。
        /// </summary>
        public static string Btn_Login {
            get {
                return ResourceManager.GetString("Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修  改 的本地化字符串。
        /// </summary>
        public static string Btn_Modify {
            get {
                return ResourceManager.GetString("Btn_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打  印 的本地化字符串。
        /// </summary>
        public static string Btn_Print {
            get {
                return ResourceManager.GetString("Btn_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注  册 的本地化字符串。
        /// </summary>
        public static string Btn_regist {
            get {
                return ResourceManager.GetString("Btn_regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保  存 的本地化字符串。
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查  询 的本地化字符串。
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登  录 的本地化字符串。
        /// </summary>
        public static string Btn_SignIn {
            get {
                return ResourceManager.GetString("Btn_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提  交 的本地化字符串。
        /// </summary>
        public static string Btn_submit {
            get {
                return ResourceManager.GetString("Btn_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解  锁 的本地化字符串。
        /// </summary>
        public static string Btn_Unlock {
            get {
                return ResourceManager.GetString("Btn_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存参数 的本地化字符串。
        /// </summary>
        public static string CacheParameter {
            get {
                return ResourceManager.GetString("CacheParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除全部 的本地化字符串。
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除日志 的本地化字符串。
        /// </summary>
        public static string ClearLogger {
            get {
                return ResourceManager.GetString("ClearLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要清除当前数据？ 的本地化字符串。
        /// </summary>
        public static string ClearTableContent {
            get {
                return ResourceManager.GetString("ClearTableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建立时间 的本地化字符串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建记录的时间 的本地化字符串。
        /// </summary>
        public static string CreateTime_Title {
            get {
                return ResourceManager.GetString("CreateTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认缓存 的本地化字符串。
        /// </summary>
        public static string DefaultCache {
            get {
                return ResourceManager.GetString("DefaultCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部  门 的本地化字符串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描  述 的本地化字符串。
        /// </summary>
        public static string Describe {
            get {
                return ResourceManager.GetString("Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌  面 的本地化字符串。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮 箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱确认 的本地化字符串。
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件参数 的本地化字符串。
        /// </summary>
        public static string EmailParameter {
            get {
                return ResourceManager.GetString("EmailParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包括 的本地化字符串。
        /// </summary>
        public static string Flt_Contains {
            get {
                return ResourceManager.GetString("Flt_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定日期之后 的本地化字符串。
        /// </summary>
        public static string Flt_Date_gt {
            get {
                return ResourceManager.GetString("Flt_Date_gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public static string Flt_Date_gte {
            get {
                return ResourceManager.GetString("Flt_Date_gte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定日期之前 的本地化字符串。
        /// </summary>
        public static string Flt_Date_lt {
            get {
                return ResourceManager.GetString("Flt_Date_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public static string Flt_Date_lte {
            get {
                return ResourceManager.GetString("Flt_Date_lte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾字符 的本地化字符串。
        /// </summary>
        public static string Flt_EndsWith {
            get {
                return ResourceManager.GetString("Flt_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string Flt_gt {
            get {
                return ResourceManager.GetString("Flt_gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public static string Flt_gte {
            get {
                return ResourceManager.GetString("Flt_gte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string Flt_IsNotSqualTo {
            get {
                return ResourceManager.GetString("Flt_IsNotSqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        public static string Flt_IsSqualTo {
            get {
                return ResourceManager.GetString("Flt_IsSqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string Flt_lt {
            get {
                return ResourceManager.GetString("Flt_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public static string Flt_lte {
            get {
                return ResourceManager.GetString("Flt_lte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 并且 的本地化字符串。
        /// </summary>
        public static string Flt_msg_and {
            get {
                return ResourceManager.GetString("Flt_msg_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Flt_msg_clear {
            get {
                return ResourceManager.GetString("Flt_msg_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选的 的本地化字符串。
        /// </summary>
        public static string Flt_msg_false {
            get {
                return ResourceManager.GetString("Flt_msg_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string Flt_msg_fliter {
            get {
                return ResourceManager.GetString("Flt_msg_fliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置筛选条件 的本地化字符串。
        /// </summary>
        public static string Flt_msg_info {
            get {
                return ResourceManager.GetString("Flt_msg_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者 的本地化字符串。
        /// </summary>
        public static string Flt_msg_or {
            get {
                return ResourceManager.GetString("Flt_msg_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个值 的本地化字符串。
        /// </summary>
        public static string Flt_msg_selectValue {
            get {
                return ResourceManager.GetString("Flt_msg_selectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中的 的本地化字符串。
        /// </summary>
        public static string Flt_msg_true {
            get {
                return ResourceManager.GetString("Flt_msg_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包括 的本地化字符串。
        /// </summary>
        public static string Flt_NotContain {
            get {
                return ResourceManager.GetString("Flt_NotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头字符 的本地化字符串。
        /// </summary>
        public static string Flt_StartsWith {
            get {
                return ResourceManager.GetString("Flt_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记密码？ 的本地化字符串。
        /// </summary>
        public static string ForgotPwd {
            get {
                return ResourceManager.GetString("ForgotPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能名称 的本地化字符串。
        /// </summary>
        public static string FuncCaption {
            get {
                return ResourceManager.GetString("FuncCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能描述 的本地化字符串。
        /// </summary>
        public static string FuncDescribe {
            get {
                return ResourceManager.GetString("FuncDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能注释 的本地化字符串。
        /// </summary>
        public static string FuncTitle {
            get {
                return ResourceManager.GetString("FuncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 综合参数 的本地化字符串。
        /// </summary>
        public static string GeneralParam {
            get {
                return ResourceManager.GetString("GeneralParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择一行数据 的本地化字符串。
        /// </summary>
        public static string Grid_MustSelectAnyRow {
            get {
                return ResourceManager.GetString("Grid_MustSelectAnyRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主  页 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string ImgScr {
            get {
                return ResourceManager.GetString("ImgScr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新人 的本地化字符串。
        /// </summary>
        public static string LastUpdateBy {
            get {
                return ResourceManager.GetString("LastUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否锁定 的本地化字符串。
        /// </summary>
        public static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定到期 的本地化字符串。
        /// </summary>
        public static string LockoutEndDateUtc {
            get {
                return ResourceManager.GetString("LockoutEndDateUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注  销 的本地化字符串。
        /// </summary>
        public static string LoggonOut {
            get {
                return ResourceManager.GetString("LoggonOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码 的本地化字符串。
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户信息 的本地化字符串。
        /// </summary>
        public static string ModifyUserProfile {
            get {
                return ResourceManager.GetString("ModifyUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络请求类型 的本地化字符串。
        /// </summary>
        public static string NetRequestType {
            get {
                return ResourceManager.GetString("NetRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        public static string OperationFailure {
            get {
                return ResourceManager.GetString("OperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}-{1}行,共{2}行 的本地化字符串。
        /// </summary>
        public static string Page_Display {
            get {
                return ResourceManager.GetString("Page_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行/页 的本地化字符串。
        /// </summary>
        public static string Page_ItemsPerPage {
            get {
                return ResourceManager.GetString("Page_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页,共{0}页 的本地化字符串。
        /// </summary>
        public static string Page_of {
            get {
                return ResourceManager.GetString("Page_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        public static string Page_Page {
            get {
                return ResourceManager.GetString("Page_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面缓存 的本地化字符串。
        /// </summary>
        public static string PageCache {
            get {
                return ResourceManager.GetString("PageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父节点Id 的本地化字符串。
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密  码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 座机号码 的本地化字符串。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机确认 的本地化字符串。
        /// </summary>
        public static string PhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Pwd {
            get {
                return ResourceManager.GetString("Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ号码 的本地化字符串。
        /// </summary>
        public static string QQNumber {
            get {
                return ResourceManager.GetString("QQNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册时间 的本地化字符串。
        /// </summary>
        public static string RegisterTime {
            get {
                return ResourceManager.GetString("RegisterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备  注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我 的本地化字符串。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色描述 的本地化字符串。
        /// </summary>
        public static string RoleDescribe {
            get {
                return ResourceManager.GetString("RoleDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string RolesManage {
            get {
                return ResourceManager.GetString("RolesManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由Action 的本地化字符串。
        /// </summary>
        public static string RouteAction {
            get {
                return ResourceManager.GetString("RouteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由Area 的本地化字符串。
        /// </summary>
        public static string RouteArea {
            get {
                return ResourceManager.GetString("RouteArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由Controller 的本地化字符串。
        /// </summary>
        public static string RouteController {
            get {
                return ResourceManager.GetString("RouteController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由参数 的本地化字符串。
        /// </summary>
        public static string RouteDefaultParam {
            get {
                return ResourceManager.GetString("RouteDefaultParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级数据缓存 的本地化字符串。
        /// </summary>
        public static string SecondDataCache {
            get {
                return ResourceManager.GetString("SecondDataCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置用户角色 的本地化字符串。
        /// </summary>
        public static string SetUserRoles {
            get {
                return ResourceManager.GetString("SetUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序号 的本地化字符串。
        /// </summary>
        public static string SortNo {
            get {
                return ResourceManager.GetString("SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风格&amp;安全 的本地化字符串。
        /// </summary>
        public static string StyleAndSafety {
            get {
                return ResourceManager.GetString("StyleAndSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人信息 的本地化字符串。
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
    }
}
