//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace one.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_FuncTree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auth_FuncTree()
        {
            this.Auth_FuncTree1 = new HashSet<Auth_FuncTree>();
            this.Auth_Roles = new HashSet<Auth_Roles>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int ModuleId { get; set; }
        public int FuncTypeId { get; set; }
        public string LevelCode { get; set; }
        public string FuncCaption { get; set; }
        public string FuncTitle { get; set; }
        public string FuncDescribe { get; set; }
        public string FuncCaptionEn { get; set; }
        public string FuncTitleEn { get; set; }
        public string FuncDescribeEn { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string DefaultParam { get; set; }
        public string RequestType { get; set; }
        public int SortNo { get; set; }
        public string ImgSrc { get; set; }
        public byte State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auth_FuncTree> Auth_FuncTree1 { get; set; }
        public virtual Auth_FuncTree Auth_FuncTree2 { get; set; }
        public virtual Pub_Metadata Pub_Metadata { get; set; }
        public virtual Pub_Metadata Pub_Metadata1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auth_Roles> Auth_Roles { get; set; }
    }
}
