//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace one.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneDotEntities : DbContext
    {
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Auth_FuncTree> Auth_FuncTree { get; set; }
        public virtual DbSet<Auth_Roles> Auth_Roles { get; set; }
        public virtual DbSet<Auth_UserClaim> Auth_UserClaim { get; set; }
        public virtual DbSet<Auth_UserInfor> Auth_UserInfor { get; set; }
        public virtual DbSet<Auth_UserLogin> Auth_UserLogin { get; set; }
        public virtual DbSet<Auth_Users> Auth_Users { get; set; }
        public virtual DbSet<Pub_Metadata> Pub_Metadata { get; set; }
        public virtual DbSet<Pub_MetaIndex> Pub_MetaIndex { get; set; }
    }
}
