//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace one.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub_MetaIndex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pub_MetaIndex()
        {
            this.Pub_Metadata = new HashSet<Pub_Metadata>();
        }
    
        public byte Id { get; set; }
        public string CategoryName { get; set; }
        public string Describe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pub_Metadata> Pub_Metadata { get; set; }
    }
}
